listening-port=25510

listening-ip=0.0.0.0
relay-ip=[IP]
external-ip=[IP]

fingerprint
use-auth-secret
static-auth-secret=

realm=[IP/DOMAIN]
server-name=[IP/DOMAIN]

no-multicast-peers

min-port=30000
max-port=30030

log-file=/var/log/turnserver/turnserver.log
simple-log
