listening-port=25510

listening-ip=0.0.0.0
relay-ip=10.136.48.37
external-ip=82.29.101.230/10.136.48.37

fingerprint
use-auth-secret
static-auth-secret=ac081578fcb248f85c57d2ff9f4674fb23118ab2282d1f500d72d280b3ab68c0

realm=dermitio.duckdns.org
server-name=dermitio.duckdns.org

no-multicast-peers

min-port=30000
max-port=30030

log-file=/var/log/turnserver/turnserver.log
simple-log
